# docker-compose.dev.yml
# Configuration pour le développement avec hot reload

version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend:/app
      - backend_venv:/app/venv
    environment:
      - PYTHONUNBUFFERED=1
      - UVICORN_RELOAD=true
    command: uvicorn server:app --host 0.0.0.0 --port 8001 --reload

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_BACKEND_URL=http://localhost:8001
    command: yarn start

  # MongoDB avec données persistantes pour le développement
  mongodb:
    volumes:
      - ./data/mongodb:/data/db
      - ./scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

volumes:
  backend_venv:
  frontend_node_modules: